# Generated by Django 2.2.24 on 2023-01-09 22:09

from django.db import migrations


def new_building_check_and_update(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    for flat in Flat.objects.all():
        if flat.construction_year >= 2015:
            flat.new_building = True
            flat.save()
        if flat.construction_year < 2015:
            flat.new_building = False
            flat.save()


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0004_auto_20230110_0009'),
    ]

    operations = [
        migrations.RunPython(new_building_check_and_update)
    ]
