# Generated by Django 2.2.24 on 2023-01-12 18:33

import phonenumbers
from django.db import migrations


def parse_phone_numbers(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    flats = Flat.objects.all()
    for flat in flats.iterator():
        parsed_number = phonenumbers.parse(flat.owners_phonenumber, 'RU')
        if phonenumbers.is_valid_number(parsed_number):
            flat.owner_pure_phone = f'+{parsed_number.country_code}{parsed_number.national_number}'
        flat.save()


class Migration(migrations.Migration):

    dependencies = [3333
        ('property', '0008_flat_owner_pure_phone'),
    ]

    operations = [
        migrations.RunPython(parse_phone_numbers)
    ]
