# Generated by Django 2.2.24 on 2023-01-12 21:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0012_auto_20230113_0011'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flat',
            old_name='owner_name',
            new_name='owner',
        ),
    ]
