# Generated by Django 2.2.24 on 2023-01-12 21:15

from django.db import migrations
from django.db.models import F


def link_flats_to_owners(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    Owner = apps.get_model('property', 'Owner')
    Owner.objects.all().update(flats=Flat.objects.filter(owner=F('name')))


class Migration(migrations.Migration):
    dependencies = [
        ('property', '0013_auto_20230113_0015'),
    ]

    operations = [
        migrations.RunPython(link_flats_to_owners)
    ]
